// export const testPriceResult = [
//   {
//     marketPrice: 29.01,
//     changePercent: 2.0400982,
//     name: "Zai Lab",
//     type: "ADR",
//     ticker: "ZLAB.O",
//     param: "usa_ZLAB",
//     currency: "USD",
//     yahooSymbol: "ZLAB",
//     yahooName: "Zai Lab Limited",
//     display: "再鼎医药（ZLAB.O）",
//   },
//   {
//     marketPrice: 80.28,
//     changePercent: 6.5569453,
//     name: "PDD",
//     type: "ADR",
//     ticker: "PDD.O",
//     param: "usa_PDD",
//     currency: "USD",
//     yahooSymbol: "PDD",
//     yahooName: "PDD Holdings Inc.",
//     display: "拼多多（PDD.O）",
//   },
//   {
//     marketPrice: 0.99,
//     changePercent: 1.0204072,
//     name: "Smart Share",
//     type: "ADR",
//     ticker: "EM.O",
//     param: "usa_EM",
//     currency: "USD",
//     yahooSymbol: "EM",
//     yahooName: "Smart Share Global Limited",
//     display: "怪兽充电（EM.O）",
//   },
//   {
//     marketPrice: 6.47,
//     changePercent: 0,
//     name: "Sinovac",
//     type: "Share",
//     ticker: "SVA.O",
//     param: "usa_SVA",
//     currency: "USD",
//     yahooSymbol: "SVA",
//     yahooName: "Sinovac Biotech Ltd.",
//     display: "科兴生物（SVA.O）12",
//   },
//   {
//     marketPrice: 1.48,
//     changePercent: 7.246379,
//     name: "Harbour Biomed",
//     type: "Share",
//     ticker: "2142.HK",
//     param: "hk_HK2142",
//     currency: "HKD",
//     yahooSymbol: "2142.HK",
//     yahooName: "HBM Holdings Limited",
//     display: "和铂医药（2142.HK）",
//   },
//   {
//     marketPrice: 0.7133,
//     changePercent: -1.6273605,
//     name: "Cepton",
//     type: "Share",
//     ticker: "CPTN.O",
//     param: "usa_CPTN",
//     currency: "USD",
//     yahooSymbol: "CPTN",
//     yahooName: "Cepton, Inc.",
//     display: "Cepton（CPTN.O）",
//   },
//   {
//     marketPrice: 12.665,
//     changePercent: 6.428574,
//     name: "Bitdeer",
//     type: "Share",
//     ticker: "BTDR",
//     param: "usa_BTDR",
//     currency: "USD",
//     yahooSymbol: "BTDR",
//     yahooName: "Bitdeer Technologies Group",
//     display: "Bitdeer（BTDR）",
//   },
//   {
//     marketPrice: 92.69,
//     changePercent: 0.6734036,
//     name: "Bloomage （华熙生物)",
//     type: "Share",
//     ticker: "688363.SH",
//     param: "hs_688363",
//     currency: "RMB",
//     yahooSymbol: "688363.SS",
//     yahooName: "Bloomage BioTechnology Corporation Limited",
//     display: "华熙生物（688363.SH）",
//   },
//   {
//     marketPrice: 22.49,
//     changePercent: 0.76164913,
//     name: "九丰能源（远丰森泰）",
//     type: "Share",
//     ticker: "605090.SH",
//     param: "hs_605090",
//     currency: "RMB",
//     yahooSymbol: "605090.SS",
//     yahooName: "Jiangxi Jovo Energy Co., Ltd",
//     display: "九丰能源（605090.SH）",
//   },
//   {
//     marketPrice: 9.65,
//     changePercent: 6.512132,
//     name: "Alphamab",
//     type: "Share",
//     ticker: "HK9966",
//     param: "hk_HK9966",
//     currency: "HKD",
//     yahooSymbol: "9966.HK",
//     yahooName: "Alphamab Oncology",
//     display: "康宁杰瑞（9966.HK）",
//   },
//   {
//     marketPrice: 2.25,
//     changePercent: 0,
//     name: "TOT",
//     type: "Share",
//     ticker: "1875.HK",
//     param: "hk_HK1875",
//     currency: "HKD",
//     yahooSymbol: "1875.HK",
//     yahooName: "TOT BIOPHARM International Company Limited",
//     display: "东曜药业（1875.HK）",
//   },
//   {
//     marketPrice: 14.69,
//     changePercent: 2.1557682,
//     name: "InventisBio (益方生物)",
//     type: "Share",
//     ticker: "688382.SH",
//     param: "hs_688382",
//     currency: "RMB",
//     yahooSymbol: "688382.SS",
//     yahooName: "InventisBio Co., Ltd.",
//     display: "益方生物（688382.SH）",
//   },
//   {
//     marketPrice: 1.12,
//     changePercent: -7.438019,
//     name: "Connect Biopharma",
//     type: "ADR",
//     ticker: "CNTB.O",
//     param: "usa_CNTB",
//     currency: "USD",
//     yahooSymbol: "CNTB",
//     yahooName: "Connect Biopharma Holdings Limited",
//     display: "康乃德（CNTB.O）",
//   },
//   {
//     marketPrice: 1.185,
//     changePercent: 4.867252,
//     name: "Zhihu",
//     type: "ADR",
//     ticker: "ZH.N",
//     param: "usa_ZH",
//     currency: "USD",
//     yahooSymbol: "ZH",
//     yahooName: "Zhihu Inc.",
//     display: "知乎（ZH.N）",
//   },
//   {
//     marketPrice: 124,
//     changePercent: 1.4729977,
//     name: "3D MEDICINES（思路迪）",
//     type: "Share",
//     ticker: "1244.HK",
//     param: "hk_HK1244",
//     currency: "HKD",
//     yahooSymbol: "1244.HK",
//     yahooName: "3D Medicines Inc.",
//     display: "3D MEDICINES（思路迪）",
//   },
//   {
//     marketPrice: 15.3,
//     changePercent: -3.530892,
//     name: "博安生物",
//     type: "Share",
//     ticker: "6955.HK",
//     param: "hk_HK6955",
//     currency: "HKD",
//     yahooSymbol: "6955.HK",
//     yahooName: "Shandong Boan Biotechnology Co., Ltd.",
//     display: "博安生物（6955.HK）",
//   },
//   {
//     marketPrice: 7.38,
//     changePercent: 5.428573,
//     name: "YMM",
//     type: "ADR",
//     ticker: "YMM.N",
//     param: "usa_YMM",
//     currency: "USD",
//     yahooSymbol: "YMM",
//     yahooName: "Full Truck Alliance Co. Ltd.",
//     display: "满帮（YMM.N）",
//   },
//   {
//     marketPrice: 16.45,
//     changePercent: 0.3660853,
//     name: "Wankai",
//     type: "Share",
//     ticker: "301216.SZ",
//     param: "hs_301216",
//     currency: "RMB",
//     yahooSymbol: "301216.SZ",
//     yahooName: "Wankai New Materials Co., Ltd.",
//     display: "万凯新材（301216.SZ）",
//   },
//   {
//     marketPrice: 2.7,
//     changePercent: 3.4482818,
//     name: "叮当健康",
//     type: "Share",
//     ticker: "9886.HK",
//     param: "hk_HK9886",
//     currency: "HKD",
//     yahooSymbol: "9886.HK",
//     yahooName: "Dingdang Health Technology Group Ltd.",
//     display: "叮当健康（9886.HK）",
//   },
//   {
//     marketPrice: 30.25,
//     changePercent: 0.66555995,
//     name: "汇通达",
//     type: "Share",
//     ticker: "9878.HK",
//     param: "hk_HK9878",
//     currency: "HKD",
//     yahooSymbol: "9878.HK",
//     yahooName: "Huitongda Network Co., Ltd.",
//     display: "汇通达网络（9878.HK）",
//   },
//   {
//     marketPrice: 7.86,
//     changePercent: 0.51150846,
//     name: "中辰股份",
//     type: "Share",
//     ticker: "300933.SZ",
//     param: "hs_300933",
//     currency: "RMB",
//     yahooSymbol: "300933.SZ",
//     yahooName: "Sinostar Cable Co., Ltd",
//     display: "中辰股份（300933.SZ）",
//   },
//   {
//     marketPrice: 69.3,
//     changePercent: 1.986764,
//     name: "Standard Chartered Bank",
//     type: "N/A",
//     ticker: "2888.HK",
//     param: "hk_HK2888",
//     currency: "HKD",
//     yahooSymbol: "2888.HK",
//     yahooName: "Standard Chartered PLC",
//     display: "Standard Chartered Bank（2888.HK）",
//   },
//   {
//     marketPrice: 62.15,
//     changePercent: 1.2214984,
//     name: "HSBC",
//     type: "N/A",
//     ticker: "0005.HK",
//     param: "hk_HK0005",
//     currency: "HKD",
//     yahooSymbol: "0005.HK",
//     yahooName: "HSBC Holdings plc",
//     display: "HSBC（0005.HK）",
//   },
//   {
//     marketPrice: 33.75,
//     changePercent: 0.44643316,
//     name: "CMB Wing Lung (CMB)",
//     ticker: "3968.HK",
//     type: "N/A",
//     param: "hk_HK3968",
//     currency: "HKD",
//     yahooSymbol: "3968.HK",
//     yahooName: "China Merchants Bank Co., Ltd.",
//     display: "CMB（3968.HK）",
//   },
//   {
//     marketPrice: 31.87,
//     changePercent: 2.773301,
//     name: "DBS",
//     type: "N/A",
//     ticker: "HK05",
//     param: "",
//     currency: "SGD",
//     yahooSymbol: "D05.SI",
//     yahooName: "DBS Group Holdings Ltd",
//     display: "DBS（D05.SG）",
//   },
//   {
//     marketPrice: 58.5725,
//     changePercent: 2.5249383,
//     name: "East West Bank",
//     type: "N/A",
//     ticker: "EWBC",
//     param: "usa_EWBC",
//     currency: "USD",
//     yahooSymbol: "EWBC",
//     yahooName: "East West Bancorp, Inc.",
//     display: "East West Bank（EWBC）",
//   },
//   {
//     marketPrice: 148.8875,
//     changePercent: 0.49780837,
//     name: "JP Morgan",
//     type: "N/A",
//     ticker: "JPM",
//     param: "usa_JPM",
//     currency: "USD",
//     yahooSymbol: "JPM",
//     yahooName: "JPMorgan Chase & Co.",
//     display: "JP Morgan（JPM）",
//   },
//   {
//     marketPrice: 85.875,
//     changePercent: 0.12242434,
//     name: "Morgan Stanley",
//     type: "N/A",
//     ticker: "MS",
//     param: "usa_MS",
//     currency: "USD",
//     yahooSymbol: "MS",
//     yahooName: "Morgan Stanley",
//     display: "Morgan Stanley（MS）",
//   },
//   {
//     marketPrice: 327.73,
//     changePercent: 0.40748075,
//     name: "Goldman Sachs",
//     type: "N/A",
//     ticker: "GS",
//     param: "usa_GS",
//     currency: "USD",
//     yahooSymbol: "GS",
//     yahooName: "The Goldman Sachs Group, Inc.",
//     display: "Goldman Sachs（GS）",
//   },
//   {
//     marketPrice: 1310.23,
//     changePercent: 1.001356,
//     name: "First Citizens",
//     type: "N/A",
//     ticker: "FCNCA",
//     param: "usa_FCNCA",
//     currency: "USD",
//     yahooSymbol: "FCNCA",
//     yahooName: "First Citizens BancShares, Inc.",
//     display: "First Citizens（FCNCA）",
//   },
//   // {
//   //   marketPrice: 21.095,
//   //   changePercent: 1.9574615,
//   //   name: "UBS",
//   //   type: "N/A",
//   //   ticker: "UBS",
//   //   param: "usa_UBS",
//   //   currency: "USD",
//   //   yahooSymbol: "UBS",
//   //   yahooName: "UBS Group AG",
//   //   display: "UBS（UBS）",
//   // },
// ];

export const testPriceResult = [
  {
    marketPrice: 28.72,
    changePercent: 3.123874,
    name: "Zai Lab",
    type: "ADR",
    ticker: "ZLAB.O",
    param: "usa_ZLAB",
    currency: "USD",
    yahooSymbol: "ZLAB",
    yahooName: "Zai Lab Limited",
    display: "再鼎医药（ZLAB.O）",
  },
  {
    marketPrice: 77.96,
    changePercent: -1.9247689,
    name: "PDD",
    type: "ADR",
    ticker: "PDD.O",
    param: "usa_PDD",
    currency: "USD",
    yahooSymbol: "PDD",
    yahooName: "PDD Holdings Inc.",
    display: "拼多多（PDD.O）",
  },
  {
    marketPrice: 0.9795,
    changePercent: -0.05102279,
    name: "Smart Share",
    type: "ADR",
    ticker: "EM.O",
    param: "usa_EM",
    currency: "USD",
    yahooSymbol: "EM",
    yahooName: "Smart Share Global Limited",
    display: "怪兽充电（EM.O）",
  },
  {
    marketPrice: 6.47,
    changePercent: 0,
    name: "Sinovac",
    type: "Share",
    ticker: "SVA.O",
    param: "usa_SVA",
    currency: "USD",
    yahooSymbol: "SVA",
    yahooName: "Sinovac Biotech Ltd.",
    display: "科兴生物（SVA.O）12",
  },
  {
    marketPrice: 1.8,
    changePercent: 21.621616,
    name: "Harbour Biomed",
    type: "Share",
    ticker: "2142.HK",
    param: "hk_HK2142",
    currency: "HKD",
    yahooSymbol: "2142.HK",
    yahooName: "HBM Holdings Limited",
    display: "和铂医药（2142.HK）",
  },
  {
    marketPrice: 0.594,
    changePercent: -10.14975,
    name: "Cepton",
    type: "Share",
    ticker: "CPTN.O",
    param: "usa_CPTN",
    currency: "USD",
    yahooSymbol: "CPTN",
    yahooName: "Cepton, Inc.",
    display: "Cepton（CPTN.O）",
  },
  {
    marketPrice: 14.24,
    changePercent: 1.6416812,
    name: "Bitdeer",
    type: "Share",
    ticker: "BTDR",
    param: "usa_BTDR",
    currency: "USD",
    yahooSymbol: "BTDR",
    yahooName: "Bitdeer Technologies Group",
    display: "Bitdeer（BTDR）",
  },
  {
    marketPrice: 89.59,
    changePercent: -0.5991356,
    name: "Bloomage （华熙生物)",
    type: "Share",
    ticker: "688363.SH",
    param: "hs_688363",
    currency: "RMB",
    yahooSymbol: "688363.SS",
    yahooName: "Bloomage BioTechnology Corporation Limited",
    display: "华熙生物（688363.SH）",
  },
  {
    marketPrice: 23.18,
    changePercent: 0.086357765,
    name: "九丰能源（远丰森泰）",
    type: "Share",
    ticker: "605090.SH",
    param: "hs_605090",
    currency: "RMB",
    yahooSymbol: "605090.SS",
    yahooName: "Jiangxi Jovo Energy Co., Ltd",
    display: "九丰能源（605090.SH）",
  },
  {
    marketPrice: 9.35,
    changePercent: -3.1088006,
    name: "Alphamab",
    type: "Share",
    ticker: "HK9966",
    param: "hk_HK9966",
    currency: "HKD",
    yahooSymbol: "9966.HK",
    yahooName: "Alphamab Oncology",
    display: "康宁杰瑞（9966.HK）",
  },
  {
    marketPrice: 2.25,
    changePercent: 0,
    name: "TOT",
    type: "Share",
    ticker: "1875.HK",
    param: "hk_HK1875",
    currency: "HKD",
    yahooSymbol: "1875.HK",
    yahooName: "TOT BIOPHARM International Company Limited",
    display: "东曜药业（1875.HK）",
  },
  {
    marketPrice: 14.4,
    changePercent: -1.0989065,
    name: "InventisBio (益方生物)",
    type: "Share",
    ticker: "688382.SH",
    param: "hs_688382",
    currency: "RMB",
    yahooSymbol: "688382.SS",
    yahooName: "InventisBio Co., Ltd.",
    display: "益方生物（688382.SH）",
  },
  {
    marketPrice: 1.08,
    changePercent: 0.9345785,
    name: "Connect Biopharma",
    type: "ADR",
    ticker: "CNTB.O",
    param: "usa_CNTB",
    currency: "USD",
    yahooSymbol: "CNTB",
    yahooName: "Connect Biopharma Holdings Limited",
    display: "康乃德（CNTB.O）",
  },
  {
    marketPrice: 1.1675,
    changePercent: 1.5217429,
    name: "Zhihu",
    type: "ADR",
    ticker: "ZH.N",
    param: "usa_ZH",
    currency: "USD",
    yahooSymbol: "ZH",
    yahooName: "Zhihu Inc.",
    display: "知乎（ZH.N）",
  },
  {
    marketPrice: 119.6,
    changePercent: -3.5483882,
    name: "3D MEDICINES（思路迪）",
    type: "Share",
    ticker: "1244.HK",
    param: "hk_HK1244",
    currency: "HKD",
    yahooSymbol: "1244.HK",
    yahooName: "3D Medicines Inc.",
    display: "3D MEDICINES（思路迪）",
  },
  {
    marketPrice: 15.58,
    changePercent: 1.8300636,
    name: "博安生物",
    type: "Share",
    ticker: "6955.HK",
    param: "hk_HK6955",
    currency: "HKD",
    yahooSymbol: "6955.HK",
    yahooName: "Shandong Boan Biotechnology Co., Ltd.",
    display: "博安生物（6955.HK）",
  },
  {
    marketPrice: 7.295,
    changePercent: 1.1789187,
    name: "YMM",
    type: "ADR",
    ticker: "YMM.N",
    param: "usa_YMM",
    currency: "USD",
    yahooSymbol: "YMM",
    yahooName: "Full Truck Alliance Co. Ltd.",
    display: "满帮（YMM.N）",
  },
  {
    marketPrice: 16.19,
    changePercent: -2.0568671,
    name: "Wankai",
    type: "Share",
    ticker: "301216.SZ",
    param: "hs_301216",
    currency: "RMB",
    yahooSymbol: "301216.SZ",
    yahooName: "Wankai New Materials Co., Ltd.",
    display: "万凯新材（301216.SZ）",
  },
  {
    marketPrice: 2.69,
    changePercent: -0.37037,
    name: "叮当健康",
    type: "Share",
    ticker: "9886.HK",
    param: "hk_HK9886",
    currency: "HKD",
    yahooSymbol: "9886.HK",
    yahooName: "Dingdang Health Technology Group Ltd.",
    display: "叮当健康（9886.HK）",
  },
  {
    marketPrice: 29.55,
    changePercent: -2.314052,
    name: "汇通达",
    type: "Share",
    ticker: "9878.HK",
    param: "hk_HK9878",
    currency: "HKD",
    yahooSymbol: "9878.HK",
    yahooName: "Huitongda Network Co., Ltd.",
    display: "汇通达网络（9878.HK）",
  },
  {
    marketPrice: 7.94,
    changePercent: 1.275509,
    name: "中辰股份",
    type: "Share",
    ticker: "300933.SZ",
    param: "hs_300933",
    currency: "RMB",
    yahooSymbol: "300933.SZ",
    yahooName: "Sinostar Cable Co., Ltd",
    display: "中辰股份（300933.SZ）",
  },
  {
    marketPrice: 69.95,
    changePercent: 0.937942,
    name: "Standard Chartered Bank",
    type: "N/A",
    ticker: "2888.HK",
    param: "hk_HK2888",
    currency: "HKD",
    yahooSymbol: "2888.HK",
    yahooName: "Standard Chartered PLC",
    display: "Standard Chartered Bank（2888.HK）",
  },
  {
    marketPrice: 62.8,
    changePercent: 1.0458531,
    name: "HSBC",
    type: "N/A",
    ticker: "0005.HK",
    param: "hk_HK0005",
    currency: "HKD",
    yahooSymbol: "0005.HK",
    yahooName: "HSBC Holdings plc",
    display: "HSBC（0005.HK）",
  },
  {
    marketPrice: 34,
    changePercent: 0.7407407,
    name: "CMB Wing Lung (CMB)",
    ticker: "3968.HK",
    type: "N/A",
    param: "hk_HK3968",
    currency: "HKD",
    yahooSymbol: "3968.HK",
    yahooName: "China Merchants Bank Co., Ltd.",
    display: "CMB（3968.HK）",
  },
  {
    marketPrice: 32.47,
    changePercent: 1.5004735,
    name: "DBS",
    type: "N/A",
    ticker: "HK05",
    param: "",
    currency: "SGD",
    yahooSymbol: "D05.SI",
    yahooName: "DBS Group Holdings Ltd",
    display: "DBS（D05.SG）",
  },
  {
    marketPrice: 57.67,
    changePercent: 1.3176389,
    name: "East West Bank",
    type: "N/A",
    ticker: "EWBC",
    param: "usa_EWBC",
    currency: "USD",
    yahooSymbol: "EWBC",
    yahooName: "East West Bancorp, Inc.",
    display: "East West Bank（EWBC）",
  },
  {
    marketPrice: 153.14,
    changePercent: 2.2501135,
    name: "JP Morgan",
    type: "N/A",
    ticker: "JPM",
    param: "usa_JPM",
    currency: "USD",
    yahooSymbol: "JPM",
    yahooName: "JPMorgan Chase & Co.",
    display: "JP Morgan（JPM）",
  },
  {
    marketPrice: 86.525,
    changePercent: 0.86850405,
    name: "Morgan Stanley",
    type: "N/A",
    ticker: "MS",
    param: "usa_MS",
    currency: "USD",
    yahooSymbol: "MS",
    yahooName: "Morgan Stanley",
    display: "Morgan Stanley（MS）",
  },
  {
    marketPrice: 326.87,
    changePercent: 0.2084652,
    name: "Goldman Sachs",
    type: "N/A",
    ticker: "GS",
    param: "usa_GS",
    currency: "USD",
    yahooSymbol: "GS",
    yahooName: "The Goldman Sachs Group, Inc.",
    display: "Goldman Sachs（GS）",
  },
  {
    marketPrice: 1352.56,
    changePercent: 2.640069,
    name: "First Citizens",
    type: "N/A",
    ticker: "FCNCA",
    param: "usa_FCNCA",
    currency: "USD",
    yahooSymbol: "FCNCA",
    yahooName: "First Citizens BancShares, Inc.",
    display: "First Citizens（FCNCA）",
  },
  {
    marketPrice: 21.065,
    changePercent: 0.7412754,
    name: "UBS",
    type: "N/A",
    ticker: "UBS",
    param: "usa_UBS",
    currency: "USD",
    yahooSymbol: "UBS",
    yahooName: "UBS Group AG",
    display: "UBS（UBS）",
  },
];
