export const testPriceResult = [
  {
    marketPrice: 28.91,
    changePercent: 4.594792,
    name: "Zai Lab",
    type: "ADR",
    ticker: "ZLAB.O",
    param: "usa_ZLAB",
    currency: "USD",
    yahooSymbol: "ZLAB",
    yahooName: "Zai Lab Limited",
    display: "再鼎医药（ZLAB.O）",
    newsParam: "ZLAB_1",
  },
  {
    marketPrice: 75.76,
    changePercent: -4.2224984,
    name: "PDD",
    type: "ADR",
    ticker: "PDD.O",
    param: "usa_PDD",
    currency: "USD",
    yahooSymbol: "PDD",
    yahooName: "PDD Holdings Inc.",
    display: "拼多多（PDD.O）",
    newsParam: "PDD_1",
  },
  {
    marketPrice: 0.9998,
    changePercent: 0.9899007,
    name: "Smart Share",
    type: "ADR",
    ticker: "EM.O",
    param: "usa_EM",
    currency: "USD",
    yahooSymbol: "EM",
    yahooName: "Smart Share Global Limited",
    display: "怪兽充电（EM.O）",
    newsParam: "EM_1",
  },
  {
    marketPrice: 6.47,
    changePercent: 0,
    name: "Sinovac",
    type: "Share",
    ticker: "SVA.O",
    param: "usa_SVA",
    currency: "USD",
    yahooSymbol: "SVA",
    yahooName: "Sinovac Biotech Ltd.",
    display: "科兴生物（SVA.O）",
    newsParam: "SVA_1",
  },
  {
    marketPrice: 1.68,
    changePercent: -6.666667,
    name: "Harbour Biomed",
    type: "Share",
    ticker: "2142.HK",
    param: "hk_HK2142",
    currency: "HKD",
    yahooSymbol: "2142.HK",
    yahooName: "HBM Holdings Limited",
    display: "和铂医药（2142.HK）",
    newsParam: "HK2142_1",
  },
  {
    marketPrice: 0.6415,
    changePercent: 4.478823,
    name: "Cepton",
    type: "Share",
    ticker: "CPTN.O",
    param: "usa_CPTN",
    currency: "USD",
    yahooSymbol: "CPTN",
    yahooName: "Cepton, Inc.",
    display: "Cepton（CPTN.O）",
    newsParam: "CPTN_1",
  },
  {
    marketPrice: 12.82,
    changePercent: -10.161182,
    name: "Bitdeer",
    type: "Share",
    ticker: "BTDR",
    param: "usa_BTDR",
    currency: "USD",
    yahooSymbol: "BTDR",
    yahooName: "Bitdeer Technologies Group",
    display: "Bitdeer（BTDR）",
    newsParam: "BTDR_1",
  },
  {
    marketPrice: 90.07,
    changePercent: 0.53577787,
    name: "Bloomage （华熙生物)",
    type: "Share",
    ticker: "688363.SH",
    param: "hs_688363",
    currency: "RMB",
    yahooSymbol: "688363.SS",
    yahooName: "Bloomage BioTechnology Corporation Limited",
    display: "华熙生物（688363.SH）",
    newsParam: "688363_1",
  },
  {
    marketPrice: 23.41,
    changePercent: 0.9922327,
    name: "九丰能源（远丰森泰）",
    type: "Share",
    ticker: "605090.SH",
    param: "hs_605090",
    currency: "RMB",
    yahooSymbol: "605090.SS",
    yahooName: "Jiangxi Jovo Energy Co., Ltd",
    display: "九丰能源（605090.SH）",
    newsParam: "605090_1",
  },
  {
    marketPrice: 9.25,
    changePercent: -1.0695227,
    name: "Alphamab",
    type: "Share",
    ticker: "HK9966",
    param: "hk_HK9966",
    currency: "HKD",
    yahooSymbol: "9966.HK",
    yahooName: "Alphamab Oncology",
    display: "康宁杰瑞（9966.HK）",
    newsParam: "HK9966_1",
  },
  {
    marketPrice: 2.25,
    changePercent: 0,
    name: "TOT",
    type: "Share",
    ticker: "1875.HK",
    param: "hk_HK1875",
    currency: "HKD",
    yahooSymbol: "1875.HK",
    yahooName: "TOT BIOPHARM International Company Limited",
    display: "东曜药业（1875.HK）",
    newsParam: "HK1875_1",
  },
  {
    marketPrice: 14.27,
    changePercent: -0.90277195,
    name: "InventisBio (益方生物)",
    type: "Share",
    ticker: "688382.SH",
    param: "hs_688382",
    currency: "RMB",
    yahooSymbol: "688382.SS",
    yahooName: "InventisBio Co., Ltd.",
    display: "益方生物（688382.SH）",
    newsParam: "688382_1",
  },
  {
    marketPrice: 1.09,
    changePercent: 0,
    name: "Connect Biopharma",
    type: "ADR",
    ticker: "CNTB.O",
    param: "usa_CNTB",
    currency: "USD",
    yahooSymbol: "CNTB",
    yahooName: "Connect Biopharma Holdings Limited",
    display: "康乃德（CNTB.O）",
    newsParam: "CNTB_1",
  },
  {
    marketPrice: 1.105,
    changePercent: -5.5555506,
    name: "Zhihu",
    type: "ADR",
    ticker: "ZH.N",
    param: "usa_ZH",
    currency: "USD",
    yahooSymbol: "ZH",
    yahooName: "Zhihu Inc.",
    display: "知乎（ZH.N）",
    newsParam: "ZH_1",
  },
  {
    marketPrice: 120.5,
    changePercent: 0.75250965,
    name: "3D MEDICINES（思路迪）",
    type: "Share",
    ticker: "1244.HK",
    param: "hk_HK1244",
    currency: "HKD",
    yahooSymbol: "1244.HK",
    yahooName: "3D Medicines Inc.",
    display: "3D MEDICINES（思路迪）",
    newsParam: "HK1244_1",
  },
  {
    marketPrice: 15.86,
    changePercent: 1.7971741,
    name: "博安生物",
    type: "Share",
    ticker: "6955.HK",
    param: "hk_HK6955",
    currency: "HKD",
    yahooSymbol: "6955.HK",
    yahooName: "Shandong Boan Biotechnology Co., Ltd.",
    display: "博安生物（6955.HK）",
    newsParam: "HK6955_1",
  },
  {
    marketPrice: 6.895,
    changePercent: -5.8060136,
    name: "YMM",
    type: "ADR",
    ticker: "YMM.N",
    param: "usa_YMM",
    currency: "USD",
    yahooSymbol: "YMM",
    yahooName: "Full Truck Alliance Co. Ltd.",
    display: "满帮（YMM.N）",
    newsParam: "YMM_1",
  },
  {
    marketPrice: 15.99,
    changePercent: -1.2353351,
    name: "Wankai",
    type: "Share",
    ticker: "301216.SZ",
    param: "hs_301216",
    currency: "RMB",
    yahooSymbol: "301216.SZ",
    yahooName: "Wankai New Materials Co., Ltd.",
    display: "万凯新材（301216.SZ）",
    newsParam: "301216_1",
  },
  {
    marketPrice: 2.59,
    changePercent: -3.7174773,
    name: "叮当健康",
    type: "Share",
    ticker: "9886.HK",
    param: "hk_HK9886",
    currency: "HKD",
    yahooSymbol: "9886.HK",
    yahooName: "Dingdang Health Technology Group Ltd.",
    display: "叮当健康（9886.HK）",
    newsParam: "HK9886_1",
  },
  {
    marketPrice: 29.5,
    changePercent: -0.16920216,
    name: "汇通达",
    type: "Share",
    ticker: "9878.HK",
    param: "hk_HK9878",
    currency: "HKD",
    yahooSymbol: "9878.HK",
    yahooName: "Huitongda Network Co., Ltd.",
    display: "汇通达网络（9878.HK）",
    newsParam: "HK9878_1",
  },
  {
    marketPrice: 7.96,
    changePercent: 0.25188893,
    name: "中辰股份",
    type: "Share",
    ticker: "300933.SZ",
    param: "hs_300933",
    currency: "RMB",
    yahooSymbol: "300933.SZ",
    yahooName: "Sinostar Cable Co., Ltd",
    display: "中辰股份（300933.SZ）",
    newsParam: "300933_1",
  },
  {
    marketPrice: 70.35,
    changePercent: 0.5718392,
    name: "Standard Chartered Bank",
    type: "N/A",
    ticker: "2888.HK",
    param: "hk_HK2888",
    currency: "HKD",
    yahooSymbol: "2888.HK",
    yahooName: "Standard Chartered PLC",
    display: "Standard Chartered Bank（2888.HK）",
    newsParam: "HK2888_1",
  },
  {
    marketPrice: 62.95,
    changePercent: 0.23885593,
    name: "HSBC",
    type: "N/A",
    ticker: "0005.HK",
    param: "hk_HK0005",
    currency: "HKD",
    yahooSymbol: "0005.HK",
    yahooName: "HSBC Holdings plc",
    display: "HSBC（0005.HK）",
    newsParam: "HK0005_1",
  },
  {
    marketPrice: 33.05,
    changePercent: -2.7941198,
    name: "CMB Wing Lung (CMB)",
    ticker: "3968.HK",
    type: "N/A",
    param: "hk_HK3968",
    currency: "HKD",
    yahooSymbol: "3968.HK",
    yahooName: "China Merchants Bank Co., Ltd.",
    display: "CMB（3968.HK）",
    newsParam: "HK3968_1",
  },
  {
    marketPrice: 32.53,
    changePercent: 0.18477842,
    name: "DBS",
    type: "N/A",
    ticker: "HK05",
    param: "",
    currency: "SGD",
    yahooSymbol: "D05.SI",
    yahooName: "DBS Group Holdings Ltd",
    display: "DBS（D05.SG）",
    newsParam: "",
  },
  {
    marketPrice: 60.63,
    changePercent: 5.0051947,
    name: "East West Bank",
    type: "N/A",
    ticker: "EWBC",
    param: "usa_EWBC",
    currency: "USD",
    yahooSymbol: "EWBC",
    yahooName: "East West Bancorp, Inc.",
    display: "East West Bank（EWBC）",
    newsParam: "EWBC_1",
  },
  {
    marketPrice: 153.85,
    changePercent: 0.30642927,
    name: "JP Morgan",
    type: "N/A",
    ticker: "JPM",
    param: "usa_JPM",
    currency: "USD",
    yahooSymbol: "JPM",
    yahooName: "JPMorgan Chase & Co.",
    display: "JP Morgan（JPM）",
    newsParam: "JPM_1",
  },
  {
    marketPrice: 91.77,
    changePercent: 6.2521634,
    name: "Morgan Stanley",
    type: "N/A",
    ticker: "MS",
    param: "usa_MS",
    currency: "USD",
    yahooSymbol: "MS",
    yahooName: "Morgan Stanley",
    display: "Morgan Stanley（MS）",
    newsParam: "MS_1",
  },
  {
    marketPrice: 336.67,
    changePercent: 2.8942544,
    name: "Goldman Sachs",
    type: "N/A",
    ticker: "GS",
    param: "usa_GS",
    currency: "USD",
    yahooSymbol: "GS",
    yahooName: "The Goldman Sachs Group, Inc.",
    display: "Goldman Sachs（GS）",
    newsParam: "GS_1",
  },
  {
    marketPrice: 1369.415,
    changePercent: 0.396997,
    name: "First Citizens",
    type: "N/A",
    ticker: "FCNCA",
    param: "usa_FCNCA",
    currency: "USD",
    yahooSymbol: "FCNCA",
    yahooName: "First Citizens BancShares, Inc.",
    display: "First Citizens（FCNCA）",
    newsParam: "FCNCA_1",
  },
  {
    marketPrice: 21.355,
    changePercent: 1.4007602,
    name: "UBS",
    type: "N/A",
    ticker: "UBS",
    param: "usa_UBS",
    currency: "USD",
    yahooSymbol: "UBS",
    yahooName: "UBS Group AG",
    display: "UBS（UBS）",
    newsParam: "UBS_1",
  },
];
